"""
Complete list of ISO 3166-1 countries for use across all forms.
Common GLOBALG.A.P. agriculture-export countries are pinned at the top.
"""

# Top countries for fruit agriculture & GLOBALG.A.P. certification
_TOP_COUNTRIES = [
    ('ZA', 'South Africa'),
    ('KE', 'Kenya'),
    ('EG', 'Egypt'),
    ('MA', 'Morocco'),
    ('TZ', 'Tanzania'),
    ('GH', 'Ghana'),
    ('CI', "Cote d'Ivoire"),
    ('ET', 'Ethiopia'),
    ('ES', 'Spain'),
    ('IT', 'Italy'),
    ('GR', 'Greece'),
    ('TR', 'Turkey'),
    ('NL', 'Netherlands'),
    ('DE', 'Germany'),
    ('FR', 'France'),
    ('GB', 'United Kingdom'),
    ('IE', 'Ireland'),
    ('BE', 'Belgium'),
    ('PL', 'Poland'),
    ('PT', 'Portugal'),
    ('CL', 'Chile'),
    ('PE', 'Peru'),
    ('CO', 'Colombia'),
    ('EC', 'Ecuador'),
    ('BR', 'Brazil'),
    ('AR', 'Argentina'),
    ('MX', 'Mexico'),
    ('CR', 'Costa Rica'),
    ('GT', 'Guatemala'),
    ('US', 'United States'),
    ('CA', 'Canada'),
    ('AU', 'Australia'),
    ('NZ', 'New Zealand'),
    ('IN', 'India'),
    ('TH', 'Thailand'),
    ('VN', 'Vietnam'),
    ('CN', 'China'),
    ('PH', 'Philippines'),
    ('ID', 'Indonesia'),
    ('PK', 'Pakistan'),
    ('IL', 'Israel'),
]

# All remaining countries alphabetically
_ALL_COUNTRIES = [
    ('AF', 'Afghanistan'),
    ('AL', 'Albania'),
    ('DZ', 'Algeria'),
    ('AD', 'Andorra'),
    ('AO', 'Angola'),
    ('AG', 'Antigua and Barbuda'),
    ('AM', 'Armenia'),
    ('AT', 'Austria'),
    ('AZ', 'Azerbaijan'),
    ('BS', 'Bahamas'),
    ('BH', 'Bahrain'),
    ('BD', 'Bangladesh'),
    ('BB', 'Barbados'),
    ('BY', 'Belarus'),
    ('BZ', 'Belize'),
    ('BJ', 'Benin'),
    ('BT', 'Bhutan'),
    ('BO', 'Bolivia'),
    ('BA', 'Bosnia and Herzegovina'),
    ('BW', 'Botswana'),
    ('BN', 'Brunei'),
    ('BG', 'Bulgaria'),
    ('BF', 'Burkina Faso'),
    ('BI', 'Burundi'),
    ('CV', 'Cabo Verde'),
    ('KH', 'Cambodia'),
    ('CM', 'Cameroon'),
    ('CF', 'Central African Republic'),
    ('TD', 'Chad'),
    ('CK', 'Cook Islands'),
    ('HR', 'Croatia'),
    ('CU', 'Cuba'),
    ('CY', 'Cyprus'),
    ('CZ', 'Czech Republic'),
    ('CD', 'DR Congo'),
    ('DK', 'Denmark'),
    ('DJ', 'Djibouti'),
    ('DM', 'Dominica'),
    ('DO', 'Dominican Republic'),
    ('TL', 'East Timor'),
    ('SV', 'El Salvador'),
    ('GQ', 'Equatorial Guinea'),
    ('ER', 'Eritrea'),
    ('EE', 'Estonia'),
    ('SZ', 'Eswatini'),
    ('FJ', 'Fiji'),
    ('FI', 'Finland'),
    ('GA', 'Gabon'),
    ('GM', 'Gambia'),
    ('GE', 'Georgia'),
    ('GD', 'Grenada'),
    ('GN', 'Guinea'),
    ('GW', 'Guinea-Bissau'),
    ('GY', 'Guyana'),
    ('HT', 'Haiti'),
    ('HN', 'Honduras'),
    ('HU', 'Hungary'),
    ('IS', 'Iceland'),
    ('IQ', 'Iraq'),
    ('IR', 'Iran'),
    ('JM', 'Jamaica'),
    ('JP', 'Japan'),
    ('JO', 'Jordan'),
    ('KZ', 'Kazakhstan'),
    ('KI', 'Kiribati'),
    ('KW', 'Kuwait'),
    ('KG', 'Kyrgyzstan'),
    ('LA', 'Laos'),
    ('LV', 'Latvia'),
    ('LB', 'Lebanon'),
    ('LS', 'Lesotho'),
    ('LR', 'Liberia'),
    ('LY', 'Libya'),
    ('LI', 'Liechtenstein'),
    ('LT', 'Lithuania'),
    ('LU', 'Luxembourg'),
    ('MG', 'Madagascar'),
    ('MW', 'Malawi'),
    ('MY', 'Malaysia'),
    ('MV', 'Maldives'),
    ('ML', 'Mali'),
    ('MT', 'Malta'),
    ('MH', 'Marshall Islands'),
    ('MR', 'Mauritania'),
    ('MU', 'Mauritius'),
    ('FM', 'Micronesia'),
    ('MD', 'Moldova'),
    ('MC', 'Monaco'),
    ('MN', 'Mongolia'),
    ('ME', 'Montenegro'),
    ('MZ', 'Mozambique'),
    ('MM', 'Myanmar'),
    ('NA', 'Namibia'),
    ('NR', 'Nauru'),
    ('NP', 'Nepal'),
    ('NI', 'Nicaragua'),
    ('NE', 'Niger'),
    ('NG', 'Nigeria'),
    ('KP', 'North Korea'),
    ('MK', 'North Macedonia'),
    ('NO', 'Norway'),
    ('OM', 'Oman'),
    ('PW', 'Palau'),
    ('PS', 'Palestine'),
    ('PA', 'Panama'),
    ('PG', 'Papua New Guinea'),
    ('PY', 'Paraguay'),
    ('QA', 'Qatar'),
    ('CG', 'Republic of the Congo'),
    ('RO', 'Romania'),
    ('RU', 'Russia'),
    ('RW', 'Rwanda'),
    ('KN', 'Saint Kitts and Nevis'),
    ('LC', 'Saint Lucia'),
    ('VC', 'Saint Vincent and the Grenadines'),
    ('WS', 'Samoa'),
    ('SM', 'San Marino'),
    ('ST', 'Sao Tome and Principe'),
    ('SA', 'Saudi Arabia'),
    ('SN', 'Senegal'),
    ('RS', 'Serbia'),
    ('SC', 'Seychelles'),
    ('SL', 'Sierra Leone'),
    ('SG', 'Singapore'),
    ('SK', 'Slovakia'),
    ('SI', 'Slovenia'),
    ('SB', 'Solomon Islands'),
    ('SO', 'Somalia'),
    ('KR', 'South Korea'),
    ('SS', 'South Sudan'),
    ('LK', 'Sri Lanka'),
    ('SD', 'Sudan'),
    ('SR', 'Suriname'),
    ('SE', 'Sweden'),
    ('CH', 'Switzerland'),
    ('SY', 'Syria'),
    ('TW', 'Taiwan'),
    ('TJ', 'Tajikistan'),
    ('TT', 'Trinidad and Tobago'),
    ('TN', 'Tunisia'),
    ('TM', 'Turkmenistan'),
    ('TV', 'Tuvalu'),
    ('UG', 'Uganda'),
    ('UA', 'Ukraine'),
    ('AE', 'United Arab Emirates'),
    ('UY', 'Uruguay'),
    ('UZ', 'Uzbekistan'),
    ('VU', 'Vanuatu'),
    ('VA', 'Vatican City'),
    ('VE', 'Venezuela'),
    ('YE', 'Yemen'),
    ('ZM', 'Zambia'),
    ('ZW', 'Zimbabwe'),
]

def get_country_choices():
    """
    Returns a list of (code, name) tuples for use in WTForms SelectField.
    Top agriculture/export countries appear first, then all remaining alphabetically.
    """
    top_codes = {c[0] for c in _TOP_COUNTRIES}
    remaining = [c for c in _ALL_COUNTRIES if c[0] not in top_codes]

    choices = [('', 'Select Country')]
    choices += _TOP_COUNTRIES
    choices += [('', '---')]  # visual separator
    choices += remaining
    return choices


def get_country_name(code):
    """Look up a country name by its ISO code."""
    all_countries = _TOP_COUNTRIES + _ALL_COUNTRIES
    for c, name in all_countries:
        if c == code:
            return name
    return code
