"""
GLOBALG.A.P. IFA v6.0 Master Control Points.

82 control points across:
- AF (All Farm Base): 19 points
- FV (Fruit & Vegetables): 26 points
- GRASP (Social Practice Add-On): 6 points

This data is seeded into each organization's control_points table
when they complete the setup wizard. Applicability is determined
by the wizard's analysis logic based on business type.
"""

GLOBALGAP_MASTER_POINTS = [
    # ── AF: All Farm Base ──
    {"code": "AF 1.1.1", "section": "AF 01 Site History & Management", "category": "Site Management", "description": "Is there a reference system for each site/field?", "compliance_criteria": "A reference system exists to identify each site/plot.", "criticality": "Minor Must", "applies_to": "all", "overlap": "LEAF, Rainforest Alliance"},
    {"code": "AF 1.2.1", "section": "AF 01 Site History & Management", "category": "Site Management", "description": "Is a risk assessment available for new sites?", "compliance_criteria": "Risk assessment for new agricultural sites documented.", "criticality": "Major Must", "applies_to": "grower", "overlap": "LEAF, Rainforest Alliance"},
    {"code": "AF 2.1", "section": "AF 02 Record Keeping & Self-Assessment", "category": "Record Keeping", "description": "Are all records kept for a minimum of 2 years?", "compliance_criteria": "Records accessible for at least 2 years.", "criticality": "Major Must", "applies_to": "all", "overlap": "BRC, IFS, SMETA"},
    {"code": "AF 2.2", "section": "AF 02 Record Keeping & Self-Assessment", "category": "Record Keeping", "description": "Does the producer carry out at least one self-assessment per year?", "compliance_criteria": "Annual internal self-assessment completed and documented.", "criticality": "Major Must", "applies_to": "all", "overlap": "BRC, IFS"},
    {"code": "AF 3.1", "section": "AF 03 Hygiene", "category": "Hygiene", "description": "Is there a hygiene risk assessment?", "compliance_criteria": "Written hygiene risk assessment available.", "criticality": "Major Must", "applies_to": "all", "overlap": "BRC, IFS, SMETA"},
    {"code": "AF 3.2", "section": "AF 03 Hygiene", "category": "Hygiene", "description": "Do workers have access to clean toilet and handwashing facilities?", "compliance_criteria": "Toilet and handwashing facilities near the work area.", "criticality": "Major Must", "applies_to": "all", "overlap": "GRASP, SMETA, Tesco Nurture"},
    {"code": "AF 3.3", "section": "AF 03 Hygiene", "category": "Hygiene", "description": "Are hygiene instructions communicated to workers?", "compliance_criteria": "Visible hygiene signage; workers briefed.", "criticality": "Minor Must", "applies_to": "all", "overlap": "BRC, SMETA"},
    {"code": "AF 4.1", "section": "AF 04 Workers Health, Safety & Welfare", "category": "Worker Welfare", "description": "Is there a health, safety and welfare risk assessment?", "compliance_criteria": "Documented risk assessment for worker H&S.", "criticality": "Major Must", "applies_to": "all", "overlap": "GRASP, SMETA, SPRING"},
    {"code": "AF 4.2", "section": "AF 04 Workers Health, Safety & Welfare", "category": "Worker Welfare", "description": "Do workers receive health and safety training?", "compliance_criteria": "Training records for all workers.", "criticality": "Major Must", "applies_to": "all", "overlap": "GRASP, SMETA, SPRING"},
    {"code": "AF 4.3", "section": "AF 04 Workers Health, Safety & Welfare", "category": "Worker Welfare", "description": "Are accident/emergency procedures in place?", "compliance_criteria": "Written emergency procedures visible at workplace.", "criticality": "Major Must", "applies_to": "all", "overlap": "SMETA, SPRING"},
    {"code": "AF 4.4", "section": "AF 04 Workers Health, Safety & Welfare", "category": "Worker Welfare", "description": "Is personal protective equipment (PPE) available?", "compliance_criteria": "PPE provided and maintained for all tasks.", "criticality": "Major Must", "applies_to": "all", "overlap": "SMETA"},
    {"code": "AF 4.5", "section": "AF 04 Workers Health, Safety & Welfare", "category": "Worker Welfare", "description": "Is first-aid equipment available and accessible?", "compliance_criteria": "First-aid kits at all work sites; trained first-aiders.", "criticality": "Minor Must", "applies_to": "all", "overlap": "SMETA"},
    {"code": "AF 5.1", "section": "AF 05 Subcontractors", "category": "Subcontractors", "description": "Is there an assessment of subcontractors for compliance?", "compliance_criteria": "Subcontractors assessed for GLOBALG.A.P. compliance.", "criticality": "Minor Must", "applies_to": "all", "overlap": "SMETA, SPRING"},
    {"code": "AF 6.1", "section": "AF 06 Waste & Pollution Management", "category": "Waste Management", "description": "Is a waste management plan in place?", "compliance_criteria": "Written waste and pollution management plan.", "criticality": "Minor Must", "applies_to": "all", "overlap": "LEAF, Rainforest Alliance"},
    {"code": "AF 6.2", "section": "AF 06 Waste & Pollution Management", "category": "Waste Management", "description": "Is waste minimized and recycled where possible?", "compliance_criteria": "Evidence of waste reduction and recycling efforts.", "criticality": "Recommendation", "applies_to": "all", "overlap": "LEAF, Rainforest Alliance"},
    {"code": "AF 7.1", "section": "AF 07 Conservation & Environment", "category": "Environment", "description": "Is an environmental management plan in place?", "compliance_criteria": "Documented plan addressing biodiversity and conservation.", "criticality": "Minor Must", "applies_to": "all", "overlap": "LEAF, Rainforest Alliance, Tesco Nurture"},
    {"code": "AF 7.2", "section": "AF 07 Conservation & Environment", "category": "Environment", "description": "Has a wildlife and biodiversity action plan been established?", "compliance_criteria": "Baseline audit of biodiversity on farm.", "criticality": "Recommendation", "applies_to": "grower", "overlap": "LEAF, Rainforest Alliance, Tesco Nurture"},
    {"code": "AF 8.1", "section": "AF 08 Complaints", "category": "Complaints", "description": "Is there a procedure for handling complaints?", "compliance_criteria": "Documented complaint procedure accessible to workers.", "criticality": "Major Must", "applies_to": "all", "overlap": "GRASP, SMETA"},
    {"code": "AF 9.1", "section": "AF 09 Recall/Withdrawal Procedure", "category": "Traceability", "description": "Is a documented recall procedure in place?", "compliance_criteria": "Written recall procedure tested at least once per year.", "criticality": "Major Must", "applies_to": "all", "overlap": "BRC, IFS"},

    # ── FV 01: Site Management & Planning ──
    {"code": "FV 01.01", "section": "FV 01 Site Management", "category": "Site Management", "description": "Have rotations and cropping plans been documented?", "compliance_criteria": "Rotation plans available for all sites.", "criticality": "Minor Must", "applies_to": "grower", "overlap": "LEAF"},
    {"code": "FV 01.02", "section": "FV 01 Site Management", "category": "Site Management", "description": "Have all production sites been identified on a map?", "compliance_criteria": "Farm map showing all production sites.", "criticality": "Minor Must", "applies_to": "grower", "overlap": "LEAF, Rainforest Alliance"},

    # ── FV 02: Soil & Substrate Management ──
    {"code": "FV 02.01", "section": "FV 02 Soil Management", "category": "Soil Management", "description": "Has a soil management plan been developed?", "compliance_criteria": "Soil maps and/or analysis records available.", "criticality": "Minor Must", "applies_to": "grower", "overlap": "LEAF"},
    {"code": "FV 02.02", "section": "FV 02 Soil Management", "category": "Soil Management", "description": "Are techniques used to improve/maintain soil structure?", "compliance_criteria": "Evidence of soil management techniques.", "criticality": "Recommendation", "applies_to": "grower", "overlap": "LEAF, Rainforest Alliance"},
    {"code": "FV 02.03", "section": "FV 02 Soil Management", "category": "Soil Management", "description": "Is soil erosion minimized?", "compliance_criteria": "Anti-erosion measures documented.", "criticality": "Minor Must", "applies_to": "grower", "overlap": "LEAF, Rainforest Alliance"},

    # ── FV 03: Fertilizer Use ──
    {"code": "FV 03.01", "section": "FV 03 Fertilizer Use", "category": "Fertilizers", "description": "Are fertilizer recommendations based on soil/leaf analysis?", "compliance_criteria": "Competent adviser records or soil analysis.", "criticality": "Major Must", "applies_to": "grower", "overlap": "LEAF, Tesco Nurture"},
    {"code": "FV 03.02", "section": "FV 03 Fertilizer Use", "category": "Fertilizers", "description": "Are records of all fertilizer applications maintained?", "compliance_criteria": "Application records: date, product, rate, operator, field.", "criticality": "Major Must", "applies_to": "grower", "overlap": "LEAF"},
    {"code": "FV 03.03", "section": "FV 03 Fertilizer Use", "category": "Fertilizers", "description": "Are fertilizers stored properly?", "compliance_criteria": "Covered, clean, dry area away from product.", "criticality": "Minor Must", "applies_to": "grower", "overlap": None},
    {"code": "FV 03.04", "section": "FV 03 Fertilizer Use", "category": "Fertilizers", "description": "Are organic fertilizers assessed for risks?", "compliance_criteria": "Risk assessment for organic fertilizer use documented.", "criticality": "Major Must", "applies_to": "grower", "overlap": None},

    # ── FV 04: Water Management ──
    {"code": "FV 04.01", "section": "FV 04 Water Management", "category": "Water Management", "description": "Has a water management plan been developed?", "compliance_criteria": "Written water management plan.", "criticality": "Minor Must", "applies_to": "all", "overlap": "LEAF, Rainforest Alliance, SPRING"},
    {"code": "FV 04.02", "section": "FV 04 Water Management", "category": "Water Management", "description": "Is irrigation water quality tested at least annually?", "compliance_criteria": "Annual water analysis report.", "criticality": "Major Must", "applies_to": "grower", "overlap": "LEAF"},
    {"code": "FV 04.03", "section": "FV 04 Water Management", "category": "Water Management", "description": "Is pre-harvest water quality tested?", "compliance_criteria": "Water risk assessment and test results.", "criticality": "Major Must", "applies_to": "grower", "overlap": None},
    {"code": "FV 04.04", "section": "FV 04 Water Management", "category": "Water Management", "description": "Is post-harvest wash water quality tested?", "compliance_criteria": "Wash water quality monitoring records.", "criticality": "Major Must", "applies_to": "packhouse", "overlap": "BRC, IFS"},

    # ── FV 05: Integrated Pest Management (IPM) ──
    {"code": "FV 05.01", "section": "FV 05 IPM", "category": "IPM", "description": "Is there an IPM system in place?", "compliance_criteria": "Documented IPM plan or equivalent.", "criticality": "Major Must", "applies_to": "grower", "overlap": "LEAF, Tesco Nurture, Rainforest Alliance"},
    {"code": "FV 05.02", "section": "FV 05 IPM", "category": "IPM", "description": "Are pest monitoring records maintained?", "compliance_criteria": "Scouting records with pest ID and threshold data.", "criticality": "Minor Must", "applies_to": "grower", "overlap": "LEAF, Tesco Nurture"},
    {"code": "FV 05.03", "section": "FV 05 IPM", "category": "IPM", "description": "Are non-chemical pest control measures used?", "compliance_criteria": "Evidence of biological/cultural controls.", "criticality": "Recommendation", "applies_to": "grower", "overlap": "LEAF, Tesco Nurture, Rainforest Alliance"},

    # ── FV 06: Plant Protection Products (PPP) ──
    {"code": "FV 06.01", "section": "FV 06 Plant Protection Products", "category": "Plant Protection", "description": "Are only registered PPPs used?", "compliance_criteria": "PPPs registered for target crop and pest in country.", "criticality": "Major Must", "applies_to": "grower", "overlap": "Tesco Nurture, Rainforest Alliance"},
    {"code": "FV 06.02", "section": "FV 06 Plant Protection Products", "category": "Plant Protection", "description": "Are all PPP applications recorded?", "compliance_criteria": "Records: date, product, target, dose, PHI, operator.", "criticality": "Major Must", "applies_to": "grower", "overlap": "Tesco Nurture"},
    {"code": "FV 06.03", "section": "FV 06 Plant Protection Products", "category": "Plant Protection", "description": "Are pre-harvest intervals (PHIs) respected?", "compliance_criteria": "PHI recorded and verified before harvest.", "criticality": "Major Must", "applies_to": "grower", "overlap": "BRC, IFS"},
    {"code": "FV 06.04", "section": "FV 06 Plant Protection Products", "category": "Plant Protection", "description": "Is PPP application equipment calibrated?", "compliance_criteria": "Annual calibration records for spraying equipment.", "criticality": "Major Must", "applies_to": "grower", "overlap": None},
    {"code": "FV 06.05", "section": "FV 06 Plant Protection Products", "category": "Plant Protection", "description": "Are PPPs stored safely?", "compliance_criteria": "Locked, ventilated store with spill containment.", "criticality": "Major Must", "applies_to": "grower", "overlap": None},
    {"code": "FV 06.06", "section": "FV 06 Plant Protection Products", "category": "Plant Protection", "description": "Are empty PPP containers disposed of properly?", "compliance_criteria": "Triple-rinsed and disposed via approved scheme.", "criticality": "Minor Must", "applies_to": "grower", "overlap": "Rainforest Alliance"},
    {"code": "FV 06.07", "section": "FV 06 Plant Protection Products", "category": "Plant Protection", "description": "Are MRL (Maximum Residue Limit) requirements known?", "compliance_criteria": "Awareness of destination-country MRLs.", "criticality": "Major Must", "applies_to": "all", "overlap": "BRC, IFS, Tesco Nurture"},
    {"code": "FV 06.08", "section": "FV 06 Plant Protection Products", "category": "Plant Protection", "description": "Are PPP residue analyses conducted?", "compliance_criteria": "Annual residue testing results available.", "criticality": "Recommendation", "applies_to": "all", "overlap": "BRC, IFS, Tesco Nurture"},

    # ── FV 07: Harvesting ──
    {"code": "FV 07.01", "section": "FV 07 Harvesting", "category": "Harvesting", "description": "Is there a harvest hygiene risk assessment?", "compliance_criteria": "Risk assessment for hygiene during harvest.", "criticality": "Major Must", "applies_to": "grower", "overlap": "BRC"},
    {"code": "FV 07.02", "section": "FV 07 Harvesting", "category": "Harvesting", "description": "Are harvest containers clean and fit for purpose?", "compliance_criteria": "Containers cleaned, maintained, food-grade only.", "criticality": "Major Must", "applies_to": "grower", "overlap": "BRC"},
    {"code": "FV 07.03", "section": "FV 07 Harvesting", "category": "Harvesting", "description": "Is produce transported hygienically from field?", "compliance_criteria": "Transport vehicles clean; produce protected.", "criticality": "Minor Must", "applies_to": "grower", "overlap": "BRC"},

    # ── FV 08: Produce Handling (Packhouse) ──
    {"code": "FV 08.01", "section": "FV 08 Produce Handling", "category": "Produce Handling", "description": "Is there a HACCP plan or food safety plan?", "compliance_criteria": "Documented HACCP/food safety plan for packhouse.", "criticality": "Major Must", "applies_to": "packhouse", "overlap": "BRC, IFS, SMETA"},
    {"code": "FV 08.02", "section": "FV 08 Produce Handling", "category": "Produce Handling", "description": "Is the packhouse hygienic and well-maintained?", "compliance_criteria": "Cleaning schedules, pest control, maintenance logs.", "criticality": "Major Must", "applies_to": "packhouse", "overlap": "BRC, IFS"},
    {"code": "FV 08.03", "section": "FV 08 Produce Handling", "category": "Produce Handling", "description": "Is cold chain management documented?", "compliance_criteria": "Temperature monitoring records for cold storage.", "criticality": "Major Must", "applies_to": "packhouse", "overlap": "BRC, IFS"},
    {"code": "FV 08.04", "section": "FV 08 Produce Handling", "category": "Produce Handling", "description": "Are quality control checks performed during packing?", "compliance_criteria": "QC records for grading, sizing, defects.", "criticality": "Minor Must", "applies_to": "packhouse", "overlap": "BRC"},
    {"code": "FV 08.05", "section": "FV 08 Produce Handling", "category": "Produce Handling", "description": "Are packaging materials food-safe and stored properly?", "compliance_criteria": "Certificates of conformity for packaging; clean storage.", "criticality": "Major Must", "applies_to": "packhouse", "overlap": "BRC, IFS"},
    {"code": "FV 08.06", "section": "FV 08 Produce Handling", "category": "Produce Handling", "description": "Is post-harvest water treatment monitored?", "compliance_criteria": "Water treatment records (chlorine, pH).", "criticality": "Major Must", "applies_to": "packhouse", "overlap": "BRC"},

    # ── FV 09: Traceability ──
    {"code": "FV 09.01", "section": "FV 09 Traceability", "category": "Traceability", "description": "Can produce be traced back to the registered farm?", "compliance_criteria": "Lot coding system linking packed product to field/grower.", "criticality": "Major Must", "applies_to": "all", "overlap": "BRC, IFS"},
    {"code": "FV 09.02", "section": "FV 09 Traceability", "category": "Traceability", "description": "Are traceability records maintained for all inputs?", "compliance_criteria": "Input supplier records (seeds, chemicals, packaging).", "criticality": "Minor Must", "applies_to": "all", "overlap": "BRC, IFS"},

    # ── GRASP Add-On: Social Practice ──
    {"code": "GRASP 1", "section": "GRASP Social Practice", "category": "Social Practice", "description": "Is there a documented workers' representative system?", "compliance_criteria": "Elected workers' representative with documented role.", "criticality": "Major Must", "applies_to": "all", "overlap": "SMETA, SPRING"},
    {"code": "GRASP 2", "section": "GRASP Social Practice", "category": "Social Practice", "description": "Is there a grievance procedure for workers?", "compliance_criteria": "Documented, accessible grievance procedure.", "criticality": "Major Must", "applies_to": "all", "overlap": "SMETA, SPRING"},
    {"code": "GRASP 3", "section": "GRASP Social Practice", "category": "Social Practice", "description": "Do employment contracts exist for all workers?", "compliance_criteria": "Written contracts; compliance with local labour law.", "criticality": "Major Must", "applies_to": "all", "overlap": "SMETA, SPRING"},
    {"code": "GRASP 4", "section": "GRASP Social Practice", "category": "Social Practice", "description": "Are payslips provided with transparent deductions?", "compliance_criteria": "Regular payslips showing gross, deductions, net.", "criticality": "Minor Must", "applies_to": "all", "overlap": "SMETA"},
    {"code": "GRASP 5", "section": "GRASP Social Practice", "category": "Social Practice", "description": "Are working hours documented and within legal limits?", "compliance_criteria": "Time records; compliance with labour law max hours.", "criticality": "Major Must", "applies_to": "all", "overlap": "SMETA, SPRING"},
    {"code": "GRASP 6", "section": "GRASP Social Practice", "category": "Social Practice", "description": "Is there a policy against child labour and forced labour?", "compliance_criteria": "Written policy; age verification system.", "criticality": "Major Must", "applies_to": "all", "overlap": "SMETA, SPRING, Rainforest Alliance"},
]
