"""Add audit_scope to SetupWizard

Revision ID: eadcb2a5c32e
Revises: d8fa91676ef2
Create Date: 2026-02-04 19:37:59.465211

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eadcb2a5c32e'
down_revision = 'd8fa91676ef2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('setup_wizards', schema=None) as batch_op:
        batch_op.add_column(sa.Column('audit_scope', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('setup_wizards', schema=None) as batch_op:
        batch_op.drop_column('audit_scope')

    # ### end Alembic commands ###
